
package com.wapwag.woss.common.sms.Intranet;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "SendSMSServiceSoap", targetNamespace = "http://10.61.98.5/webservice/sms/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SendSMSServiceSoap {


    /**
     * ���Ͷ���
     * 
     * @param mobile
     * @param sendLevel
     * @param dnd
     * @param message
     * @param subcategory
     * @param expiredTime
     * @param preSendTime
     * @return
     *     returns boolean
     */
    @WebMethod(operationName = "SendSMS", action = "http://10.61.98.5/webservice/sms/SendSMS")
    @WebResult(name = "SendSMSResult", targetNamespace = "http://10.61.98.5/webservice/sms/")
    @RequestWrapper(localName = "SendSMS", targetNamespace = "http://10.61.98.5/webservice/sms/", className = "com.wapwag.woss.common.sms.SendSMS")
    @ResponseWrapper(localName = "SendSMSResponse", targetNamespace = "http://10.61.98.5/webservice/sms/", className = "com.wapwag.woss.common.sms.SendSMSResponse")
    public boolean sendSMS(
        @WebParam(name = "mobile", targetNamespace = "http://10.61.98.5/webservice/sms/")
        String mobile,
        @WebParam(name = "message", targetNamespace = "http://10.61.98.5/webservice/sms/")
        String message,
        @WebParam(name = "subcategory", targetNamespace = "http://10.61.98.5/webservice/sms/")
        String subcategory,
        @WebParam(name = "preSendTime", targetNamespace = "http://10.61.98.5/webservice/sms/")
        XMLGregorianCalendar preSendTime,
        @WebParam(name = "expiredTime", targetNamespace = "http://10.61.98.5/webservice/sms/")
        XMLGregorianCalendar expiredTime,
        @WebParam(name = "sendLevel", targetNamespace = "http://10.61.98.5/webservice/sms/")
        Integer sendLevel,
        @WebParam(name = "DND", targetNamespace = "http://10.61.98.5/webservice/sms/")
        Integer dnd);

}
