
package com.wapwag.woss.common.sms.Intranet;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "SendSMSService", targetNamespace = "http://10.61.98.5/webservice/sms/", wsdlLocation = "http://10.61.98.5:600/SendSMSService.asmx?wsdl")
public class SendSMSService
    extends Service
{

    private final static URL SENDSMSSERVICE_WSDL_LOCATION;
    private final static WebServiceException SENDSMSSERVICE_EXCEPTION;
    private final static QName SENDSMSSERVICE_QNAME = new QName("http://10.61.98.5/webservice/sms/", "SendSMSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://10.61.98.5:600/SendSMSService.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        SENDSMSSERVICE_WSDL_LOCATION = url;
        SENDSMSSERVICE_EXCEPTION = e;
    }

    public SendSMSService() {
        super(__getWsdlLocation(), SENDSMSSERVICE_QNAME);
    }

    public SendSMSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), SENDSMSSERVICE_QNAME, features);
    }

    public SendSMSService(URL wsdlLocation) {
        super(wsdlLocation, SENDSMSSERVICE_QNAME);
    }

    public SendSMSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SENDSMSSERVICE_QNAME, features);
    }

    public SendSMSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SendSMSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SendSMSServiceSoap
     */
    @WebEndpoint(name = "SendSMSServiceSoap")
    public SendSMSServiceSoap getSendSMSServiceSoap() {
        return super.getPort(new QName("http://10.61.98.5/webservice/sms/", "SendSMSServiceSoap"), SendSMSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSMSServiceSoap
     */
    @WebEndpoint(name = "SendSMSServiceSoap")
    public SendSMSServiceSoap getSendSMSServiceSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://10.61.98.5/webservice/sms/", "SendSMSServiceSoap"), SendSMSServiceSoap.class, features);
    }

    /**
     * 
     * @return
     *     returns SendSMSServiceSoap
     */
    @WebEndpoint(name = "SendSMSServiceSoap12")
    public SendSMSServiceSoap getSendSMSServiceSoap12() {
        return super.getPort(new QName("http://10.61.98.5/webservice/sms/", "SendSMSServiceSoap12"), SendSMSServiceSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SendSMSServiceSoap
     */
    @WebEndpoint(name = "SendSMSServiceSoap12")
    public SendSMSServiceSoap getSendSMSServiceSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://10.61.98.5/webservice/sms/", "SendSMSServiceSoap12"), SendSMSServiceSoap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (SENDSMSSERVICE_EXCEPTION!= null) {
            throw SENDSMSSERVICE_EXCEPTION;
        }
        return SENDSMSSERVICE_WSDL_LOCATION;
    }

}
